# Generated by Django 5.2.9 on 2026-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacktype', models.CharField(max_length=50)),
                ('feedbacktext', models.TextField()),
                ('rating', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
