# Generated by Django 6.0.7 on 2026-07-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excuses', '0002_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
