# Generated by Django 5.2.9 on 2026-03-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='body_preview',
            field=models.TextField(),
        ),
    ]
